// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package data

import (
	"Week04/internal/acg/service/http"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	db, cleanup, err := NewDB()
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := NewRedis()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	server, err := http.New()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app, cleanup3, err := NewApp(db, client, server)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
